services:
  - type: web
    name: Verify-AI
    runtime: node
    repo: https://github.com/camerartsp/Verify-AI
    plan: free
    buildCommand: npm install && npm run install-puppeteer
    startCommand: node index.js
    envVars:
      - key: PORT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    region: oregon
version: "1"