name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --shm-size 2gb

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    # Remover a etapa de lint se não for necessária
    # - name: Run lint
    #   run: npm run lint

    - name: Run unit tests
      run: npm run test

    - name: Test analyzeNews function
      run: node test-analyze-news.js
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}